### ISSUE TITLE
Array JSON Body Types

### ISSUE THREAD

**Issue by moutansos** [rest-nvim/tree-sitter-http#15]
Hello, I seem to be having an issue with the syntax highlighting requests after I have an array body request. For example:

```http
### This call is fine
POST http://example.com/api/v1/endpoint
Content-Type: application/json

{
  "foo": "bar"
}

### This call is not
POST http://example.com/api/v1/bad-endpoint
Content-Type: application/json

[
  {
    "foo": "bar"
  }
]

### This call is now broken
POST http://example.com/api/v1/broken-endpoint
Content-Type: application/json

{
  "foo": "bar"
}
```

Shows up like this:
![image](https://github.com/rest-nvim/tree-sitter-http/assets/7742806/64e2a90b-b0bc-4a0c-bb94-3ae0ec5ec33a)

My best guess is that the grammar only sees `{ ... }` as a valid json body and not `[ .... ]`

Let me know if there's more info I can provide or any way I could help. Thanks!

**Comment by NTBBloodbath** [comment]
I really don't know how I never evaluated that use case. Nice finding!

The parser also needs a restructuring so it would be very good to do both and save some time. I'll try to find some spare time during my weekend :p

**Comment by moutansos** [comment]
Awesome! Thanks for the fixes!
