### ISSUE TITLE
Feature: Spread query parameters into multiple lines

### ISSUE THREAD

**Issue by KalleChen** [rest-nvim/tree-sitter-http#18]
Is there a way to let query strings more human-readable as this vscode extension does? 

https://marketplace.visualstudio.com/items?itemName=humao.rest-client
<img width="750" alt="Screen Shot 2022-06-15 at 10 17 26 AM" src="https://user-images.githubusercontent.com/48475056/173723362-d541931d-2609-4e3f-a118-ff94aa70d28d.png">

**Comment by NTBBloodbath** [comment]
**Note**: transferred from `rest.nvim` repository as this has something to do with the parser grammar.
