### ISSUE TITLE
Tree-sitter Parse Error

### ISSUE THREAD

**Issue by kevintraver** [rest-nvim/tree-sitter-http#21]
```GET http://httpbin.org/get?input={"0":{"json":{"id":12345}}}```

Throws the following error:

```
    ERROR: The tree-sitter node at the range [0:0 - 1:0] has a syntax error and cannot be parsed
    Error executing lua: .../share/nvim/lazy/rest-nvim/lua/rest-nvim/parser/init.lua:89: attempt to index local 'node' (a nil value)
stack traceback:
	.../share/nvim/lazy/rest-nvim/lua/rest-nvim/parser/init.lua:89: in function 'look_behind_until'
	.../share/nvim/lazy/rest-nvim/lua/rest-nvim/functions.lua:63: in function 'exec'
```

Escaping the URL does not work either:

```GET http://httpbin.org/get?input=%7B%220%22%3A%7B%22json%22%3A%7B%22id%22%3A109018%7D%7D%7D```

**Comment by NTBBloodbath** [comment]
NB: this has something to do with the `query_param` node grammar not capturing JSON objects.

**Comment by lhiamgeek** [comment]
same problem here: 

I got a query like following:

GET http://localhost:8080/version/list?iPageNum=0&iPageSize=5&szVersion=1.0.2&iApkChannel=0|60

[rest.nvim] ERROR: The tree-sitter node at the range [0:0 - 173:0] has a syntax error and cannot be parsed, 

the parser can not parse `|60`

**Comment by fdaciuk** [comment]
Just fyi: I have the same error trying to use and email in URL:

```http
GET https://myapi.com/email/a@b.com
```

Same error when try to encode (because of `%` char).

**Comment by fdaciuk** [comment]
Just fyi: I have the same error trying to use and email in URL:

```http
GET https://myapi.com/email/a@b.com
```

Same error when try to encode (because of `%` char).

My solution for now: use a variable instead =)

```http
@email="a@b.com"
GET https://myapi.com/email/{{email}}
```

**Comment by fdaciuk** [comment]
@NTBBloodbath I got a different scenario with same error:

```http
@base_url="mydomain.com"
GET https://{{base_url}}/test
```

If I use `base_url` at start, it works:

```http
@base_url="https://mydomain.com"
GET {{base_url}}/test
```

I can't use a subdomain tho.

Should I file a new issue?
