### ISSUE TITLE
[BUG] The '{' and '}' in the target_url are recognized as ERROR

### ISSUE THREAD

**Issue by askfiy** [rest-nvim/tree-sitter-http#35]
The following request will not resolve successfully:

```
GET http://localhost:5000/index?userProperty={"name": "age"}
```

This kind of query_param with JSON information is also encountered in the actual development process, but it is not currently possible to parse

**Comment by ccoVeille** [comment]
I'm sorry but shouldn't it be properly encoded in the URL then?

GET http://localhost:5000/index?userProperty=%7B%22name%22%3A%20%22age%22%7D

I don't expect tree-sitter to parse invalid code

**Comment by NTBBloodbath** [comment]
Probably an issue caused by #32?

**Comment by ccoVeille** [comment]
You might be right, BTW.

When I saw the PR, I was surprised about the format.

**Comment by NTBBloodbath** [comment]
I think at some point the parser is going to need an additional handmade tree-sitter C scanner to avoid ambiguities and make everything much more flexible. If anyone has a better solution than that, you are welcome to make a PR or post it here

**Comment by askfiy** [comment]
Expect it to display nodes instead of ERRORs, and that there should be a specific program that handles URL encoding when the request is actually sent.
