### ISSUE TITLE
[Feature Request] Improve captures for URL

### ISSUE THREAD

**Issue by igorlfs** [rest-nvim/tree-sitter-http#39]
Hello!

I've noticed that currently, a URL is captured as a single "group", within neovim:

![image](https://github.com/user-attachments/assets/ba3642a6-d243-4e83-ae4a-50d01ff9c1ed)

`:Inspect` anywhere in the URL shows that

```
  - @string.special.url.http links to @string.special.url http
```

IIRC, earlier iterations were able to distinguish symbols like `&` and `?` and key-value pairs in the query's params, providing a richer experience when it comes to highlighting.

**Comment by igorlfs** [comment]
> I'm surprised it's a valid syntax
> 
> Shouldn't you have `HTTP/1.1` or something like that at the end of the line.
> 
> Maybe it explains the difference you are facing

Nope, appending a `HTTP/1.1` at the end makes no difference. 

Most [examples from rest-nvim](https://github.com/rest-nvim/rest.nvim/tree/main/spec/examples) omit this parameter. Intellij's [spec](https://www.jetbrains.com/help/idea/exploring-http-syntax.html) also frequently omits the parameter as well.

**Comment by boltlessengineer** [comment]
Sorry for late reply. I completely forgot to subscribe this repo.

That is valid syntax and yes, previous version supported more detailed target url parsing.
I removed that feature since [v3.0 release](https://github.com/rest-nvim/tree-sitter-http/pull/38) because it is so hard to implement well.

If tools like `rest.nvim` supports non-urlencoded target urls, we can’t really support url parsing and non-encoded syntax at same time.
Think about injecting variables inside the url, that’s already invalid according to RFC spec.

So `tree-sitter-http` won’t be responsible to parse and validate the URL.

Tons of issues in `tree-sitter-http` and `rest.nvim` were made because of this. Some are fixed before the v3 release but still.

**Comment by igorlfs** [comment]
> Sorry for late reply. I completely forgot to subscribe this repo.

No worries!

> If tools like `rest.nvim` supports non-urlencoded target urls, we can’t really support url parsing and non-encoded syntax at same time. Think about injecting variables inside the url, that’s already invalid according to RFC spec.

I see. Just to be clear: what you're suggesting is to use, for instance

```http
###

@FOO=bar

GET http://localhost:3000/api?foo={{FOO}}
```

**Comment by boltlessengineer** [comment]
You can use with whatever style you want.
```
GET http://localhost:3000/api?foo=bar
```
is still fine. but both `tree-sitter-http` and `rest.nvim` won’t understand the URI syntax.
`rest.nvim` will send the whole variable injected URI to underlying request clients (e.g. `curl`), and only those clients will parse the URI and catch the syntax issue if there are any.

**Comment by ccoVeille** [comment]
Let me try to rephrase to make sure I understand.

tree-sitter-http parses the text and identifies zone. The parsing of the URL parameters is out of tree-sitter-http responsibilities. the client is the one that need to parse the URL parameters.

So my guess is that if the bug reported here about neovim wrongly reporting the URL parameters when using tree-sitter-http has to be moved to neovim.

**Comment by boltlessengineer** [comment]
@ccoVeille correct.

When I say “request clients”, I mean clients that actually runs the request.
Currently `rest.nvim` only uses `curl` (or `libcurl` which is implemented internally as an example but disabled by default) as a request client.
If there are something wrong in URI syntax, `curl` will report errors and that will be passed to `rest.nvim`.

**Comment by boltlessengineer** [comment]
Closing this issue as wontfix.
Parsing URI from http parser is too hard, not worth it.
