### ISSUE TITLE
HTTP Version is still get recognized as target_url if file not ending with a ### separator

### ISSUE THREAD

**Issue by hvdute** [rest-nvim/tree-sitter-http#46]
Issue: HTTP version is still recognized as `target_url` if the request file does not end with a `###` separator. It appears that only the last request in file is affected. I have included two examples below.

* **Without ending with ###, the last request won't be able to run:**

  <img width="1680" alt="image" src="https://github.com/user-attachments/assets/8676b782-1bf9-4cc5-8850-f4a3840c6a31" />

* **With `###` ending, it can parse HTTP version correctly:**

  <img width="1680" alt="image" src="https://github.com/user-attachments/assets/a0759e58-ade3-4618-bcad-d15663b32d26" />

**Comment by boltlessengineer** [comment]
This issue (seems to be a duplicate of #44) has been fixed from #45. Do you still have issue after updating the http parser?

**Comment by hvdute** [comment]
Yesterday before submitting this issue I've tried updating parser, nvim-treesitter to latest but it still happen. Today I tried uninstalling and pin the latest commit then it worked. Let me close the issue.
